name: Android CI

on:

  pull_request:

    branches-ignore:

      - ''

  push:

    branches-ignore:

      - ''

  workflow_dispatch:

  

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

      with:

        fetch-depth: 0

    - name: set up JDK 17

      uses: actions/setup-java@v3

      with:

        distribution: 'temurin'

        java-version: 17

    - name: Build debug.apk

      run: |

        ./gradlew assembleRelease
